dir = "./db"
network = "tcp"
address = "127.0.0.1"
port = 8001
dbname = "blockchain"
logfile = "./immudb.log"
pidfile = "./pid.log"
mtls = false
detached = false
auth = true
no-histograms = false
consistency-check = true
devmode = false
admin-password = "g{4@LAGvv!"
maintenance = false
signingKey = ""
token-expiry-time = 1
web-server = true
web-server-port = 8002
pgsql-server = false
pgsql-server-port = 5432